apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv
  labels:
    type: local
spec:
  storageClassName: downloads
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/mount-server"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: media
spec:
  storageClassName: downloads
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

