apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-mergerfs-pv
  labels:
    type: local
spec:
  storageClassName: downloads-mergerfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/mergerstorage"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-mergerfs
  namespace: media
spec:
  storageClassName: downloads-mergerfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

