---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app mautrix-whatsapp
  namespace: social
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    image:
      repository: dock.mau.dev/mautrix/whatsapp
      tag: v0.10.7

    service:
      main:
        ports:
          http:
            port: 29318

    podAnnotations:
      secret.reloader.stakater.com/reload: *app

    ingress:
      main:
        annotations:
        enabled: true
        hosts:
          - host: &host "mautrix-whatsapp.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    probes:
      liveness:
        enabled: false
        custom: true
        spec:
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 5
          httpGet:
            path: /api/v1/health
            port: 3000
      readiness:
        enabled: false
        custom: true
        spec:
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 5
          httpGet:
            path: /api/v1/health
            port: 3000

    persistence:
      registration:
        enabled: true
        name: *app
        readOnly: true
        mountPath: /data/registration.yaml
        subPath: registration.yaml
        type: configMap
      config:
        enabled: true
        name: *app
        type: configMap
        readOnly: true
        mountPath: /data/config.yaml
        subPath: config.yaml

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi

