---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
namespace: social
configMapGenerator:
  - name: mautrix-whatsapp
    files:
      - config.yaml=config/config.yaml
      - registration.yaml=config/registration.yaml
generatorOptions:
  disableNameSuffixHash: true
