apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - https://raw.githubusercontent.com/kubernetes-sigs/node-feature-discovery/refs/tags/v0.13.1/deployment/base/nfd-crds/nfd-api-crds.yaml
  - helm-release.yaml
