apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openhaystack
  namespace: networking
  annotations:
    coredns.io/hostname: "ohs.${SECRET_DEV_DOMAIN}"
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: traefik
  rules:
    - host: &host "ohs.${SECRET_DEV_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: openhaystack
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *host
      secretName: *host
---
apiVersion: v1
kind: Service
metadata:
  name: openhaystack
  namespace: networking
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: openhaystack
  namespace: networking
subsets:
  - addresses:
      - ip: "10.2.111.13"
    ports:
      - port: 8080
---
