---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: signal-api
  namespace: social
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      rumpreis:
        type: statefulset
        containers:
          app:
            image:
              repository: docker.io/bbernhard/signal-cli-rest-api:latest
              tag: latest
            env:
              TZ: ${TIMEZONE}
              MODE: "native"
              AUTO_RECEIVE_SCHEDULE: "0 22 * * *"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      app:
        controller: signal-api
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.home.arpa/enabled: "true"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-basic-auth@kubernetescrd

        hosts:
          - host: &uri "signal-api.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *uri
            secretName: *uri

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /home/.local/share/signal-cli
