apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtop-config
  labels:
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
