---
creation_rules:
  - encrypted_regex: '^(data|stringData)$'
    age: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
  - path_regex: components/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
  - path_regex: clusters/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
