apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
    xxx.server: | 
         dh274.com {
              hosts {
                   10.2.111.29 dh274.com
                   fallthrough
              }
          }

