apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik
    includeSelectors: false
resources:
  - helm-release.yaml
  - middlewares
  - ingresses
  - secret.sops.yaml
 # - coredns-custom.yaml
