apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: transcoder
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/dragonhunter274/transcode-gui
  ref:
    branch: main
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/dragonhunter274/mediawiki-chart/master/flux/helmrelease.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: transcoder
  namespace: utilities
spec:
  interval: 10m
  chart:
    spec:
      chart: ./helm/transcoder
      sourceRef:
        kind: GitRepository
        name: transcoder
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/dragonhunter274/transcode-gui
      tag: main

    media:
      readOnly: false
      volumeSpec:
        csi:
          driver: jellyfin-cache.csi.io
          readOnly: false
          volumeAttributes:
            server: jellyfin-cache.media.svc.cluster.local

    staging:
      size: 50Gi

    env:
      encodeThreads: 2
      vmafDefault: 95
      sampleDuration: "4sec"

    ingress:
      enabled: true
      className: traefik
      host: transcoder.${SECRET_DEV_DOMAIN}
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.home.arpa/enabled: "true"
        traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authentik@kubernetescrd
      tls:
        - secretName: transcoder-tls
          hosts:
            - transcoder.${SECRET_DEV_DOMAIN}

    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 4Gi
