---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hoarder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      hoarder:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: 0.23.1
            env:
              BROWSER_WEB_URL: http://hoarder-chrome.utilities.svc.cluster.local:9222
              CRAWLER_DOWNLOAD_BANNER_IMAGE: true
              CRAWLER_ENABLE_ADBLOCKER: true
              CRAWLER_STORE_SCREENSHOT: true
              DATA_DIR: /data
              DISABLE_SIGNUPS: true
              COREPACK_INTEGRITY_KEYS: 0
              OPENAI_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: hoarder-secret
                    key: openai-apikey
              MEILI_ADDR: http://hoarder-meilisearch.utilities.svc.cluster.local:7700
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: hoarder-secret
                    key: meilisearch_master_key
              NEXTAUTH_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: hoarder-secret
                    key: encryption_key
              NEXTAUTH_URL: https://hoarder.${SECRET_DEV_DOMAIN}
              DISABLE_NEW_RELEASE_CHECK: true
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi

      chrome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
            args:
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            securityContext:
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi

      meilisearch:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.13.3
            env:
              MEILI_NO_ANALYTICS: true
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: hoarder-secret
                    key: meilisearch_master_key
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi

    service:
      app:
        controller: hoarder
        ports:
          http:
            port: 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700

    ingress:
      app:
        className: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &uri "hoarder.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *uri
            secretName: *uri

    persistence:
      data:
        existingClaim: hoarder-data
        advancedMounts:
          hoarder:
            app:
              - path: /data
                subPath: hoarder
          meilisearch:
            app:
              - path: /meili_data
                subPath: meilisearch
