apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
commonLabels:
  app.kubernetes.io/name: &app hoarder
  app.kubernetes.io/instance: *app
resources:
  - helmrelease.yaml
  - hoarder-pvc.yaml
  - secret.sops.yaml
