apiVersion: v1
kind: Secret
metadata:
    name: hoarder-secret
    namespace: utilities
stringData:
    meilisearch_master_key: ENC[AES256_GCM,data:dx10WWxkR+Hdy8uOYp9wKUyxHVq2Bt4AJxikzt6HZc0=,iv:iGitMeDkRt/ePCezw2ZnADPTzUPtgJ9ttRiWjbs3ANg=,tag:+NvpNzYXFtGiTwrR76zD3g==,type:str]
    encryption_key: ENC[AES256_GCM,data:F2uVNISbTv0/CF/6ysb6fKXKAV9fhuL1CHOPjPcekMk=,iv:9wLfAp/PP1hJUUs64vSdVypkOvy2yKrQrt79p+BdoBM=,tag:E8h3dp0QA610SmsHEZV3Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTEVjeVZRL21tS1lsYWRa
            M1VNT0w1YUkxTGdkT2dPNTMrbmNBSkZmeEh3CjdON0dpTllmZkR6NVQ5d0NwVXJq
            MWxhaGxwZkUxNmJtRjBKL1ZYOHVIVDgKLS0tIE4yUmFQanpNbDB1TkxnblhMNmFM
            anQ2WmV4Qlk3czVYY0pGTlhsR1FIUkUKznnuUwUQpPEZ8csWkGU9r5EFSLhaxl5z
            32S8wso4p9r9DGXAzVolbk68fDhieGewZSGBluIYXhs7bP3tWSweSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T16:35:51Z"
    mac: ENC[AES256_GCM,data:oFknVb5avAp9w9wtTJ+Grm/8J8a/d3rBx56dyylxUrMFFQzO11/83wKSJDPGxb1sQhBSm7A+7G9GlT6LAnuka5rQgJHIO3SpxKHl3rd3CTLevrEk6t43SWovDfEsT0FaOxPltwkj7Ux1vENUMmkS9XXS+9zgBf88A6qkDn3GMdc=,iv:kHlLz4coht1ScOWMN3cFnlCgEAncCXzUUjhHCKMnae0=,tag:c9KdBJcXhJ3h5zkOv+JQNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
