apiVersion: v1
kind: Secret
metadata:
    name: hoarder-secret
    namespace: utilities
stringData:
    meilisearch_master_key: ENC[AES256_GCM,data:dx10WWxkR+Hdy8uOYp9wKUyxHVq2Bt4AJxikzt6HZc0=,iv:iGitMeDkRt/ePCezw2ZnADPTzUPtgJ9ttRiWjbs3ANg=,tag:+NvpNzYXFtGiTwrR76zD3g==,type:str]
    encryption_key: ENC[AES256_GCM,data:F2uVNISbTv0/CF/6ysb6fKXKAV9fhuL1CHOPjPcekMk=,iv:9wLfAp/PP1hJUUs64vSdVypkOvy2yKrQrt79p+BdoBM=,tag:E8h3dp0QA610SmsHEZV3Jw==,type:str]
    openai-apikey: ENC[AES256_GCM,data:Zqj8VT0Wgd2mcnzUv8i3yEvqbPRmFp4Tw83hDAPL/JIYrSDOswk9JULMhG1bUQFPzt3bINJLfgZn7uEPo/ouMU6cNOGqCFSxT3tQadhmpOYBvrVXKHJiZQyzmiTZs9Y8RTLQMiJZ8wqPpkZ4aZVs5UjL5cRr+SDcAWHXjiStnPexqzLRJQew2kW/hOfnR1SOlAez7O+LADtKhYM1NGD5Src8lhY=,iv:F1ISukhMiOrQcCAmQvATzreH5qefJF8Yem54ZPfrjlU=,tag:nKGzVf4aVHOVDlIZg8lySA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTEVjeVZRL21tS1lsYWRa
            M1VNT0w1YUkxTGdkT2dPNTMrbmNBSkZmeEh3CjdON0dpTllmZkR6NVQ5d0NwVXJq
            MWxhaGxwZkUxNmJtRjBKL1ZYOHVIVDgKLS0tIE4yUmFQanpNbDB1TkxnblhMNmFM
            anQ2WmV4Qlk3czVYY0pGTlhsR1FIUkUKznnuUwUQpPEZ8csWkGU9r5EFSLhaxl5z
            32S8wso4p9r9DGXAzVolbk68fDhieGewZSGBluIYXhs7bP3tWSweSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T18:00:52Z"
    mac: ENC[AES256_GCM,data:OPxDNb+1pj6lgO3A93Y3/hk0gz8WuEDCr1E6dh/SxIrqmKEoeziRrcP0duv8AMatrxpvP9W+9LJGViCMw/2hm+SxFH8gONXfLX6s+FEtcJ/zq+GnFcosurkhBMR2J921kzuO1v86prRhUyOHhsPd9v9i6eFS282DNff2uBqkdmM=,iv:YnRlc63o3ACfXbBxIxrAm/pMViO117XtnXAI1M90Kic=,tag:ApZWPv1YEI+AdbEoAvdLjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
