apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: zeropod-system
    name: zeropod-system
  spec:
    finalizers:
    - kubernetes

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: zeropod-node
    namespace: zeropod-system

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: zeropod:pod-updater
  rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "update"]

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: zeropod:runtimeclass-installer
  rules:
  - apiGroups: ["node.k8s.io"]
    resources: ["runtimeclasses"]
    verbs: ["create", "delete", "update"]

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: zeropod:pod-updater
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: zeropod:pod-updater
  subjects:
  - kind: ServiceAccount
    name: zeropod-node
    namespace: zeropod-system

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: zeropod:runtimeclass-installer
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: zeropod:runtimeclass-installer
  subjects:
  - kind: ServiceAccount
    name: zeropod-node
    namespace: zeropod-system

- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    labels:
      app.kubernetes.io/name: zeropod-node
    name: zeropod-node
    namespace: zeropod-system
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/name: zeropod-node
    template:
      metadata:
        labels:
          app.kubernetes.io/name: zeropod-node
      spec:
        containers:
        - args:
          - -metrics-addr=:8080
          - -status-labels=true
          - -debug
          command:
          - /zeropod-manager
          image: ghcr.io/ctrox/zeropod-manager:v0.6.1
          imagePullPolicy: IfNotPresent
          name: manager
          ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
              - SYS_ADMIN
              - NET_ADMIN
            privileged: true
          volumeMounts:
          - mountPath: /run/zeropod
            name: zeropod-run
          - mountPath: /hostproc
            name: hostproc
          - mountPath: /sys/fs/bpf
            name: bpf
        initContainers:
        - args:
          - -criu-image=ghcr.io/ctrox/zeropod-criu:v3.19
          - -runtime=k3s
          image: ghcr.io/ctrox/zeropod-installer:v0.11.1
          imagePullPolicy: IfNotPresent
          name: installer
          volumeMounts:
          - mountPath: /etc/containerd
            name: containerd-etc
          - mountPath: /run/containerd
            name: containerd-run
          - mountPath: /opt/zeropod
            name: zeropod-opt
          - mountPath: /run/systemd
            name: systemd-run
          - mountPath: /etc/criu
            name: criu-etc
        - args:
          - mount | grep "/sys/fs/bpf type bpf" || mount -t bpf bpf /sys/fs/bpf
          command:
          - /bin/sh
          - -c
          - --
          image: alpine:3.21.3
          imagePullPolicy: IfNotPresent
          name: prepare-bpf-fs
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /sys/fs/bpf
            mountPropagation: Bidirectional
            name: bpf
        nodeSelector:
          zeropod.ctrox.dev/node: "true"
        serviceAccountName: zeropod-node
        tolerations:
        - operator: Exists
        volumes:
        - hostPath:
            path: /var/lib/rancher/k3s/agent/etc/containerd/
          name: containerd-etc
        - hostPath:
            path: /run/k3s/containerd
          name: containerd-run
        - hostPath:
            path: /var/lib/rancher/k3s/agent/containerd
          name: zeropod-opt
        - hostPath:
            path: /run/zeropod
          name: zeropod-run
        - hostPath:
            path: /run/systemd
          name: systemd-run
        - hostPath:
            path: /etc/criu
          name: criu-etc
        - hostPath:
            path: /proc
            type: Directory
          name: hostproc
        - hostPath:
            path: /sys/fs/bpf
            type: Directory
          name: bpf
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate

