apiVersion: v1
kind: Secret
metadata:
    name: nix-builder-provisioner
    namespace: utilities
type: Opaque
stringData:
    STORE_HOST: ENC[AES256_GCM,data:r/F8yfgSUJFrHwk=,iv:hTz6cEFkAJINTFqGdkA0UxF8mqamidQ+f+Z/rDxBewc=,tag:XBd0Dp8YySZjK6eUHFZWxA==,type:str]
sops:
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WFFRSUJ0ZWhVbTVKdGZB
            WVJoa0h0N2JDY0RQdEpLMVgrb3pYZUt4Qkc4ClNXUGZQM0hqQ3daa0dqTXplanUz
            MkVwaG52UUZjcDg3T1Z6VnIrdG55WDgKLS0tIHA0NnAzc1NWN3djVWlCWFhnY2tF
            ejZvSW9xMmQzaDRWb1JxclgzeUdJeVEKbyPUgKYJd4goDejJxHJY422lygfLadtk
            xBjZCG6BzyQgmBdpDm7I7QCHBayQAE/kCqk/1qB7Eu4oye5cYYRWtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T15:35:13Z"
    mac: ENC[AES256_GCM,data:eFnlqcVXDjy8U9uuak4L+BEV1LHLC+WJMA1qSca/XLs5Xs00XPDSuMocqEOxSO6KlgAmV6jn1PoLOiX7L4Vbud/yI/LA6VWstbzYoZK3r6gBWNY8a5wPVaB44I6h526Iz+K0c9Q+bIbVJhMzT4UmUOHF3QRwNNeeeoaSNefAdks=,iv:LKykVs7Pdx240pe1gso0Z3NfX3kNreZksF8WSTJlt9k=,tag:WCEvju/K+CLOKHZJXFIX/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
