apiVersion: v1
kind: Secret
metadata:
    name: nix-builder-provisioner
    namespace: nix-builder-provisioner
type: Opaque
stringData:
    STORE_HOST: ENC[AES256_GCM,data:r/F8yfgSUJFrHwk=,iv:hTz6cEFkAJINTFqGdkA0UxF8mqamidQ+f+Z/rDxBewc=,tag:XBd0Dp8YySZjK6eUHFZWxA==,type:str]
sops:
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WFFRSUJ0ZWhVbTVKdGZB
            WVJoa0h0N2JDY0RQdEpLMVgrb3pYZUt4Qkc4ClNXUGZQM0hqQ3daa0dqTXplanUz
            MkVwaG52UUZjcDg3T1Z6VnIrdG55WDgKLS0tIHA0NnAzc1NWN3djVWlCWFhnY2tF
            ejZvSW9xMmQzaDRWb1JxclgzeUdJeVEKbyPUgKYJd4goDejJxHJY422lygfLadtk
            xBjZCG6BzyQgmBdpDm7I7QCHBayQAE/kCqk/1qB7Eu4oye5cYYRWtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T15:10:13Z"
    mac: ENC[AES256_GCM,data:Q1wFqigRqCDNAp0zF1SaXpMEXV+qkN/DGLiDkukMqa213Mn8MyaGy3txMQO3E2WwOi/CB44YQpWjW0yAjs/2T+P+XSMXiCP+XvtjV4qHIjTW7+bGA+WmQR9OrnxVTDpHiRF14OYH+p9M0WJTueLnPvjbNa0BYbNXHEGJkRVCbnQ=,iv:eAWgFbazsEjmSOr1CWQ+l5OBmzEwElWX21yTuhLs3LA=,tag:1HnV3WkDNCBKPz1AOca4xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
