apiVersion: v1
kind: Secret
metadata:
    name: nix-builder-provisioner
    namespace: utilities
type: Opaque
stringData:
    STORE_HOST: ENC[AES256_GCM,data:ZmLwUvjU5Ka9Qzc=,iv:OqYH4r9qA/p5pMIS3/8ssIWs5E9IU7MHP60yMAe+/WI=,tag:O2qX1cTc+xjxvnZMaNeTog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WFFRSUJ0ZWhVbTVKdGZB
            WVJoa0h0N2JDY0RQdEpLMVgrb3pYZUt4Qkc4ClNXUGZQM0hqQ3daa0dqTXplanUz
            MkVwaG52UUZjcDg3T1Z6VnIrdG55WDgKLS0tIHA0NnAzc1NWN3djVWlCWFhnY2tF
            ejZvSW9xMmQzaDRWb1JxclgzeUdJeVEKbyPUgKYJd4goDejJxHJY422lygfLadtk
            xBjZCG6BzyQgmBdpDm7I7QCHBayQAE/kCqk/1qB7Eu4oye5cYYRWtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T12:03:03Z"
    mac: ENC[AES256_GCM,data:izQST9uEu1A+k4zEjfgpROpu9u2+GUAiklucyTdCtrxDP7xnbwLGxXoPLZ7C/O+xw5psrOKgpxWVbIdDOEqOUHbZT64qKB+ljM2PYlPSH8xdjTBSwSTQoqR92JOepq1PkrpvSy3S+3YeuaTuqNq6WrlIEulomdWx4e1xeLJiKDY=,iv:PQ8YdVrkcukYNEZh3s/lbFfTNh4BirJWDeDDiWvDAyc=,tag:yqX5CwT5fcXiavEK6cOFYQ==,type:str]
    version: 3.13.1
