---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authentik-ldap
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        name: bjw-s
        kind: HelmRepository
        namespace: flux-system
  values:
    global:
      fullnameOverride: *app
    automountServiceAccountToken: false
    controller:
      type: deployment
      replicas: 2
    image:
      repository: ghcr.io/goauthentik/ldap
      tag: "2023.10.5@sha256:4f0722da4bd67e4bd261154556bc93d461c0b0f3784ab907c4177504140e5322"
    podLabels:
      egress.home.arpa/nginx-external: "allow"
    env:
      TZ: "Europe/Berlin"
      AUTHENTIK_HOST: "https://authentik.auth.svc.cluster.local"
      AUTHENTIK_HOST_BROWSER: "https://auth.dh274.com"
      AUTHENTIK_TOKEN:
        valueFrom:
          secretKeyRef:
            name: authentik-ldap
            key: token
    service:
      main:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        ports:
          http:
            enabled: false
          ldap-tcp:
            enabled: true
            port: 389
            targetPort: 3389
            protocol: TCP
          ldap-udp:
            enabled: true
            port: 389
            targetPort: 3389
            protocol: UDP
          ldaps-tcp:
            enabled: true
            port: 636
            targetPort: 6636
            protocol: TCP
          ldaps-udp:
            enabled: true
            port: 636
            targetPort: 6636
            protocol: UDP
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 6000Mi
