apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: akm
  namespace: auth
spec:
  releaseName: akm
  chart:
    spec:
      chart: akm
      version: 0.13.2
      sourceRef:
        kind: HelmRepository
        name: akm-registry
        namespace: flux-system
  interval: 6m
  install:
    remediation:
      retries: 7
  upgrade:
    remediation:
      retries: 7
