---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rumnotifier
  namespace: utilities
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      signal-api:
        type: statefulset
        containers:
          app:
            image:
              repository: ghcr.io/dragonhunter274/rum_notifier
              tag: latest
            env:
              TZ: ${TIMEZONE}
              API_URL: "https://rum.${SECRET_DEV_DOMAIN}"
              APPRISE_URLS: "${SECRET_RUMNOTIFIER_APPRISE_URLS}"
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities: {add: ["CHOWN", "SYS_ADMIN"]}
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 500Mi

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /config
