# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_S3_ENDPOINT: ENC[AES256_GCM,data:f19VIkA0y5+Dcn69VZqF9sFhLpQgLVnp234W1/mOqXJnMZ5lHcD/T7kqgQ==,iv:FHWguTqrmsk8u6sMKKHy0Gy4sujunIQO4lf44uMCIDs=,tag:zqk9Yh465YvizrQbNZRBww==,type:str]
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:PFqdiWVYqNW6ojX0wSU=,iv:EzOBiXvfUuBi8FAlylQSmSqlfv1RdtvnCqIMwHyyBaQ=,tag:84xPFsUUo8bh0eXUULeTSQ==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:dCvgj80Ul+sM6LP8gOfM,iv:rjzYpZxZV6Yp32XvIqYc+QcZY/jMSiQ7CycswIQ6UAo=,tag:FfMTC+y9wAjfO3vqJt+vnQ==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:xdI3lZWbLEo2G6nV3g==,iv:qoXx1k3C3L/2zajus81gjhgOcM4e9MFCxNjevwQ/w3E=,tag:u/xvVI4s6te7mO2cTUenrw==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:S/0v3eAFKrznLcuUfkfDYx/ReVPaHfU5nH3CyZtiiCY211gyyVb9Zw==,iv:ok/1pTAA8ByTlzD596WNqrsFIyhqvDaxSvkr3v3xsyg=,tag:+Zvp9hEJr1m+y3SS4ACJbw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:XwFYGiV8a6v0WUkgmKQVFA35,iv:rFa6gpdcEppKtDnE4hKJWeq9bAyFy8kOPqL0fzU8o+M=,tag:IkYHLsG8pxDqQjSP/jgScw==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:KOaK8mUC,iv:gZ5aBrUadFJD6tpjRz6Jcimx+2Zyd9ezeon1F++wYmY=,tag:QIrx0oQDBlRm6Fikivj+0A==,type:str]
    SECRET_PROD_DOMAIN_KF: ENC[AES256_GCM,data:phn1dQXM,iv:2uujVPeQiSjcvmyGzBIb15m6nA85nu3Ej+Tf9qVzSt0=,tag:pmwfMqHRALOt6H96wWvgug==,type:str]
    SECRET_PROD_DOMAIN_KFD: ENC[AES256_GCM,data:Rl23g6dS,iv:qdBsZYe3UvnvnWsgilCKp6PlOJugCyJAaaNfYPQIQvw=,tag:CcmW7q95ukAeJWPQ8t7CMQ==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:SJLov75ai0YV,iv:yGRS4jnvN9wirde7OvYdLVB3xLAyn06ExBnS++E9BQ0=,tag:+4sD2Dkz1btynEMiv9Sdzg==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:LeDTtTV3y+I=,iv:awBk9jjWnzgQ4JGGeK9ZZsdspVLPxZnTnCuo0IdWRBo=,tag:q7eQZI44hSugHIrkWIt0cA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:43Stew==,iv:FULxLT7EaeIGM1NeO2WdT3P7+2scM6JkkXTZpeOV9X4=,tag:1bsQ5XM16jctozzSi1e4Ew==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:iYbMW5tlgtM=,iv:L841g2x2O3R0zv861pvED9F5cF/F83hY7EVNYgPb+jk=,tag:/SOfhYZDGsGeSu05STPRLg==,type:str]
    SECRET_TEST_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:b+kVozl0,iv:dRBwwtYYmowtJvZ3i3mHaNPaWBmbIgPbWqiDp7hEW1M=,tag:W8IGRn6KfwWagpeATwvvLQ==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:VL6kZX0jtVke,iv:Dl85iRT9c3FvTd9pWvF5+/KInbm14hKaWuM+S8sdgKg=,tag:IMSe2gYtNkIaAon56+Ujsg==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:RCMNX4fBSA==,iv:BXyccAl8FWDVyYKuggc0/Mz2Cf5LOlf/vUNmiww808Y=,tag:ADzEWclVWXWthKXMcvVDVg==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:YU9henrgddo=,iv:qow9lxnCrFy+DoDi7v0FG7qIdFBvXKwyK9SCrqsFnms=,tag:zL7+Bhb4eatuKqfuLjjCqQ==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:vW7XWERS5n3KXQ==,iv:rIVfZWaWNls5YV+gVGcJpjb8xa7lVPRUlGc+o1RUvmo=,tag:TA3CVEtDHHWIHwsKCTJgNw==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:TfhSiqDc1QSS,iv:Wkp3caOo/VLtF/YaTtmqmEnE+r+5o9H92t5fdDMqRl4=,tag:PQcFTOFbtY1s33ssIqDPcw==,type:str]
    SECRET_LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:IO9DKq9VilHy,iv:w5T1g6haACujch9v8BjJ/bCOgLKS2fSiZRvQWKK4XXc=,tag:B/rOhCGaCsM5+dRTcSbCKw==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:51dLrK498RMd,iv:2iOEnnit6JNfhnBtQy0lowBHIlJwzjWzBRDEORsVETo=,tag:iDa3NVqkJRfTPRPfca+7ag==,type:str]
    SECRET_SMTP_FROM_NAME: ENC[AES256_GCM,data:m+EsS1d1y/uV2g==,iv:xheZpFk/7uOME63hF+sAeDZBa/gvPzmLSe3Usuq2Szg=,tag:6k+/FbaCUCr3NNg1UGmNag==,type:str]
    SECRET_SMTP_FROM_ADDR: ENC[AES256_GCM,data:L2uLj7PJCmYlgGEAGA==,iv:E1a7cwJ6GKSXLZxO5u2lNue4tXKnv0X/FyhUxxXeiJI=,tag:koQuN4ZJqU6+Hw7cMHGguQ==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:Hae0uqXdXb8H,iv:MNuSd8aI6XfXLuQANw8Oow7+akjBL7wD4sqzEX8ee6I=,tag:TDnrUcxt2VZA8qz7pxnquw==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:kc4ghRqaEd0=,iv:0twJRHLBuEY+1GlG2dEQjw4xa6wnUYFekYscK8P76uY=,tag:Tgwh7NRAzZJbNkMLuV7akQ==,type:str]
    SECRET_SMTP_SECURITY: ENC[AES256_GCM,data:vNDTnQZUI+pC,iv:L5xwTZXUti0+yJTD1hcdSjk/FVH3kfeGyRKXKRsAjCQ=,tag:nQRz+GTsvDCQiiHnErog3g==,type:str]
    SECRET_SMTP_PORT: ENC[AES256_GCM,data:RIwyTBoKdz9o/A==,iv:CvSa2LsMoTxiCo3+wZHuuOauPJVMc7BM+ITBpAing+Y=,tag:IPRYNtx/oR5MITJ0ewp1pA==,type:str]
    SECRET_YUBICO_CLIENT_ID: ENC[AES256_GCM,data:aDVy4bJaGV2dpA==,iv:wMCl6qtSn2KqpnIMMD6OQvQM9ZrtX3c+b9hK6cHIB3c=,tag:l1BPqYF38rIYRJylN6siJQ==,type:str]
    SECRET_YUBICO_KEY: ENC[AES256_GCM,data:M9kpuFejCaTSjA==,iv:h7EVWKW5nrBkH388BsJp9u/WbpLF5cGTzBeLAYuNoYs=,tag:lDMju2PwWd/BPQpe3ZGIrQ==,type:str]
    SECRET_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:MaTZKsoSUFZoY2N9+rIaGuIeIHbTeP0BZp2HX6bZ,iv:sGAT8srusb3d+cf3ZBayKKC12QvVsfkOfQOx0l+TUKQ=,tag:jfq4fd/PYNzGiVZT1cnObw==,type:str]
    SECRET_PUSHOVER_EMAIL: ENC[AES256_GCM,data:BDX++w8tMpVviCm8FUF0uYnV,iv:n3eaTu+Vil521iY6hL45NkHVrBuSq/suI1IbLCuZdfw=,tag:zx9AfpO9Vr5rywUWxKZLZw==,type:str]
    SECRET_PUSHOVER_DEV_TOKEN: ENC[AES256_GCM,data:G4I5v9jV4//AHrjBs97t9OufQgG+pV6xW/lqsfT9,iv:jU/579j2hABrG8lOpbNxFmYiz7TPfdJOHAv0kxgX9yw=,tag:VqYQmVFj7EHqv86f5P0WcQ==,type:str]
    SECRET_PUSHOVER_PROD_TOKEN: ENC[AES256_GCM,data:tUEXd+BcDg6EIYIUZhDEmyRxkmCDioaHKpOFyYlk,iv:XfIYLZWS/YHjalsld6q6ng7lLOR4HNHbZVCKbX0Yoto=,tag:ebZ+dCRihEkxTNMFcirl5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQ2VvTVU1YzNJTTNhNnZ3
            OGxzT2dUeWpkYm0wQTYxVE9WSXVlMytES0FjCmhWK29IQzA1Q08rZTI3ZklBa0ta
            OVc5OFdtMHVXWFE3RWVSSTQ5Z25rUTQKLS0tIDU3M0F5ZDBHdGI3WkluK3B3Ni9U
            MWk1ZEVQMXJHRlVROXF4YngxcXkwdEEKiR6bpU39PZLnNEu8g+FzAdRNX9zoDz8Q
            h1sES08ar4HuJoCDbrNbMMGXl7f52T6wV6n9WTgrwpTI2W5e8K1bOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-28T11:44:42Z"
    mac: ENC[AES256_GCM,data:oiI1iUPUnWpwprTMQ5bWtGfK4NafW9PrRle/jiNbyuyOkDPXC+de/5WaTEzeJIQo4XOpT9DIG4rsvRbDI6NQr7Vm05dwTmrzd2uf83j7HGU0Zq2o/17HKBF18lGLUP3DmChE6HlKAA1f3saPmcXXxAvJnIi9HrHgO9TRxWFluOo=,iv:VNS3u9hWJb0ylIPUbl/YHJ8Y79P+8uzNRpQCz82Buks=,tag:EwjgGNTdoOlyaQTqJPGJ9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
