---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nfs-client-provisioner
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: ghcr.io/dragonhunter274/nfs-subdir-external-provider:4.0.19
          volumeMounts:
            - name: nfs-client-root
              mountPath: /opt/persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: ${NAS_ADDR}
            - name: NFS_PATH
              value: /nfs/provisioner
      volumes:
        - name: nfs-client-root
          nfs:
            server: ${NAS_ADDR}
            path: /nfs/provisioner
