---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey-operator
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: valkey-operator
      version: v0.0.61-chart
      sourceRef:
        kind: HelmRepository
        name: valkey-operator
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
