apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: profilarr-config-volume
    labels:
      app: profilarr
      snapshot.home.arpa/enabled: "true"
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 4Gi

