# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja
  namespace: utilities
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  driftDetection:
    mode: enabled
  values:
    controllers:
      vikunja:
        containers:
          app:
            image:
              repository: vikunja/vikunja
              tag: 1.0.0@sha256:096e8d4067483b770f3899e20655d6235b0b4c6c9c6ec5ef39bae5b270e1a92a
              pullPolicy: IfNotPresent
            command: [./vikunja]
            env:
              VIKUNJA_SERVICE_PUBLICURL: https://todo.${SECRET_DEV_DOMAIN}/
              VIKUNJA_SERVICE_FRONTENDURL: https://todo.${SECRET_DEV_DOMAIN}/
              VIKUNJA_DEFAULTSETTINGS_TIMEZONE: Europe/Berlin

              VIKUNJA_DATABASE_TYPE: postgres
              VIKUNJA_DATABASE_HOST: vikunja-postgresql-rw
              VIKUNJA_DATABASE_DATABASE: vikunja
              VIKUNJA_DATABASE_USER: vikunja
              VIKUNJA_DATABASE_PASSWORD:
                secretKeyRef:
                  name: vikunja-postgresql-app
                  key: password

              VIKUNJA_KEYVALUE_TYPE: redis
              VIKUNJA_REDIS_ENABLED: "true"
              VIKUNJA_REDIS_HOST: vikunja-valkey:6379
              VIKUNJA_REDIS_PASSWORD:
                secretKeyRef:
                  name: vikunja-valkey-secret
                  key: password

              VIKUNJA_AUTH_LOCAL: "false"
            envFrom:
              - secretRef:
                  name: vikunja-env
            securityContext:
              readOnlyRootFilesystem: true
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          hostAliases:
            - ip: 10.43.88.142
              hostnames:
                - auth.${SECRET_DEV_DOMAIN}

    service:
      vikunja:
        controller: vikunja
        ports:
          http:
            port: 3456

    persistence:
      files:
        suffix: files
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 2Gi
        retain: true
        globalMounts:
          - path: /app/vikunja/files
      config:
        type: secret
        name: vikunja-config
        globalMounts:
          - path: /etc/vikunja/config.yaml
            subPath: config.yaml
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache

    ingress:
      vikunja:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: todo.${SECRET_DEV_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: vikunja
                  port: http
        tls:
          - hosts:
              - todo.${SECRET_DEV_DOMAIN}
            secretName: vikunja-tls

    secrets:
      env:
        stringData:
          VIKUNJA_SERVICE_JWTSECRET: ${jwt_secret}
      config:
        stringData:
          # language=yaml
          config.yaml: |
            auth:
              openid:
                enabled: true
                redirecturl: https://todo.${SECRET_DEV_DOMAIN}/auth/openid/
                providers:
                  - name: Authentik
                    authurl: https://auth.${SECRET_DEV_DOMAIN}/application/o/vikunja/
                    logouturl: https://auth.${SECRET_DEV_DOMAIN}/application/o/vikunja/end-session/
                    clientid: ${oauth_client_id}
                    clientsecret: ${oauth_client_secret}
