apiVersion: v1
kind: Secret
metadata:
    name: vikunja-valkey-secret
    namespace: utilities
stringData:
    password: ENC[AES256_GCM,data:84KeyeeDfpkO+zsQ6BNI4nFHjBlnGQS9gSTiSg/MyarrJOwu3evQzYdKULk=,iv:uAMrvhoJzJFQHEXSXV5KL6i3zLkt5VgstEmfs9aJ078=,tag:NmoAHX4CzhdfeFNyGp2wQg==,type:str]
sops:
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQUgwWnJNSXJEeW9MMnNu
            a2xLVmhVN0F1Sjc2QmY3TkYwMHVaa1ZSc3lJCmh2aU0vdm0zbmkzK3lweUZtbjgx
            WmZhK3M1MlBJWGpFUExCeXhGUWJIZ3MKLS0tIHJqK0VRL0NuK3VlT1plQmI0WXpB
            OGNLQnpIWGE0YTVjVVhQZG1FOHQ2aFEKGMvrmeGanmtJw58xfCmLNSH2nQ4LE4a8
            95fVow/yh4LMgfCIRXe5tI4Upm9da5uJR5CgOvRtjZrP8+If7TSdvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T15:37:16Z"
    mac: ENC[AES256_GCM,data:hkiRrNzp0Lc34LtFQhhI8fqbtXTof/Xty1MnVAabPN0i4EKH4mhwWPe8cgtT71Tk+ZapSY9wflFn1eZ5oIRTtvq4UMHVlCR5k9pAzgJ3gCEF6ts3JK/5BZ1SnDmSDKb1ahVe2jQ+IDSthsjfoq0ltdK953im9sKAE6FzNUB0WKk=,iv:e3Ve9n8MAGB7uI5nNkqhqumIRllcWHLefBgIVsgafH8=,tag:qXg5GrKjnJ+UVzchZl+kGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
