apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games
commonLabels:
  app.kubernetes.io/name: &app gravitas2
  app.kubernetes.io/instance: *app
resources:
  - helmrelease.yaml
  - secret.sops.yaml
