apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gravitas2
  namespace: games
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: '4.23.1'
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: flux-system
      interval: 1h
  values:
    image:
      repository: ghcr.io/dragonhunter274/minecraft-server
      pullPolicy: Always
    resources:
      requests:
        cpu: 1
        memory: 8G
      limits:
        memory: 16G
    minecraftServer:
      eula: "TRUE"
      version: "1.20.1"
      type: "FORGE"
      whitelist: DragonHunter274
      ops: DragonHunter274
      maxWorldSize: 29999984
      levelType: 'tfc:overworld'
      spawnProtection: 0
      pvp: true
      memory: 8000M
      serviceType: LoadBalancer
      rcon:
        enabled: true

    extraEnv:
      PACKWIZ_URL: "https://dragonhunter274.github.io/gravitas2-packwiz/pack.toml"
    persistence:
      dataDir:
        enabled: true
        storageClass: local-path
        Size: 10G
