apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - ro
    - port=2049
    - mountport=2049
    - nolock
  nfs:
    server: 10.43.217.235
    path: /

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-nfs
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  volumeName: jellyfin-cache-nfs
  storageClassName: ""
