---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: &name nextcloud-config
    namespace: storage
    labels:
      snapshot.home.arpa/enabled: "true"
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 1Gi
