apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
    namespace: storage
stringData:
    postgres_username: ENC[AES256_GCM,data:0Z0APEICkUWe,iv:VDJzcx07yu0IgraHn+t2aJQ+8agDzXFTIapolIwtbWs=,tag:hrG/UMmzW+WElmWgXzjDvA==,type:str]
    postgres_password: ENC[AES256_GCM,data:i6ULBKGAvEkhGhXJlw8=,iv:wg9XWwzcw2REFuW94jDKzlxn6TqvLJuekNJBHJ8bUXI=,tag:t+M+jftQvXXWI/gwUd0OpA==,type:str]
    nextcloud-username: ENC[AES256_GCM,data:+FXyl+24/RpY,iv:lzq3JmYVkdZXZJN8GEEyV+Oq8vxHm7cAzANNUEwYzcY=,tag:Fk8XTAHd4Ls/sY4eewO35g==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:iHzjsCMhT/7BqgwY,iv:S8kx5aWEn4sZnaUOG13vHk6w8jCHwt8Nd11b9xwpB+s=,tag:8mRIjwemwChxyJIJsE2NHw==,type:str]
    nextcloud-token: ENC[AES256_GCM,data:Qi/C87PpfDU9GWIu50kRSk9UcQXAOP36DlcvaQK+td3lmrT4JeWwbopfMaQ=,iv:0kA3YonfgUpvZ7Hd/up2I65gt+767PEteRw283a37XA=,tag:YLhsUf4qmyqhf5m8nLhPuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRThIU0lFQVorZTV5SXp0
            dnVMNnJ6bGVsSmk3NFBnbkxUSkM0a3AxS2xRCkxKUWlvUTEwWjFSQTl6MGp0ZGZB
            eFNmTGEyS0ZHdVRPdWwxWVZwdm80SnMKLS0tIGo2a2k2OFZJODBock8yRUlPZXBo
            WGxyREdWNSsvWklrNFpaNVpwYTdTUXMKmbyv5ERzSdlGh49xaFFRv38VICdeJqN1
            USlgnCd2LcfJ5S/k6qdzighUBQkACVAD5jBimyL56/BalFJTkHTc/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-04T18:57:18Z"
    mac: ENC[AES256_GCM,data:HXj8u7qozANrUEP1EoLxK27vXhsfS9fUTfHTMStFHYEhvzFw9RuPbFvrJoi/GaUSR2ZOtb7K0Cl2+NTzsLLwpygbH+VmZP5zoNr8g6edW+0KR4acm6pnChLs3jGzocBElJzLpzhzE6XAMSlpoKGrTjhzgiWRhxc0zgg8euV+xos=,iv:iPhz8pnkrJmPQwwUVbIlVkC4Uoeh0+0C5tIaV2atqUs=,tag:r+nhCvBnmFtaZjVDWzJduw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
