---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-pv
  namespace: media
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: media-smb-volume
    volumeAttributes:
      source: "${SECRET_CIFS_SHARE}/media"
    nodeStageSecretRef:
      name: smb-secrets
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-jellyfin-pvc
spec:
  volumeName: media-library-pv
  storageClassName: smb
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
