apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-pv
  labels:
    type: local
spec:
  storageClassName: media-smb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/media-smb"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-pvc 
  namespace: media
spec:
  storageClassName: media-smb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

