apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    username: ENC[AES256_GCM,data:ivXXYJjvP10=,iv:yI2Lkop+vXOkVwux4hqSBlc4cVYc3TPpEJAUCTbcRLg=,tag:SKWYOpKajkN611zrFCOnxw==,type:str]
    password: ENC[AES256_GCM,data:/sAI1fWfJqhl4vY=,iv:Lq55cKuW7ArHJkhHMt6gl3A7bIbr+Xg6wHgVHXoMljw=,tag:cAOwDYVUVNoNYl8zJJ3paQ==,type:str]
    host: ENC[AES256_GCM,data:baB+,iv:rke3auHDfPhn8jR84HK4q5XUOAit+7DtHNiJz3MzeoA=,tag:29IDIBpxK/iujQ758KhKRA==,type:str]
    port: ENC[AES256_GCM,data:v9qsPw==,iv:WKpYV/KYCPQPGuJ5QV5SoyUeguh1UwyTiYB2U7YoZRE=,tag:cY7v4DSaX+ZJcico00299w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWE1WS0NVekhybDhqbG1B
            YklKY1V5MWQwNXN3ZGYxY3Z2WFQrNzRQQ21ZCjhVUEZBMzM0c1hROWhzbC9pZmRY
            eVRYQWNrRW0rM1RJNExRUXlvdnpZSjgKLS0tIDNQQlN1TkNMTGVwc2hqaVhvdUdP
            TFlZMzRuTW5qakNaWWJvbmtCTXVreUkKVDTCdyT72+eEwgMPQaeYaChTso2Qchvn
            4gQby7fyI3GUfwBLc1vEeAhZqWi+0mputkvIeh01Rp2GS6Gou1bChg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-20T13:56:42Z"
    mac: ENC[AES256_GCM,data:1XDTg8MU8JJdwV4Jo+ZmdbLt0dwvcO2vubrMjZ2TDsUgjC2E4P5I0SFGvJQMUZHQoHGuyohCTtabBvjpAfTqAC8elFLta1zgeDvBASPkhxEP8mx4r2XZO+yZ4AuUKMgCNPW7Av6jD6S1RYCujftUw+INclHlwmsDHtjh4gQl82Q=,iv:EkPU0tQpCBiInzs2Yd1LvPImtvqy9RKkH3LDc9DbjxA=,tag:6Eex/8NG5sm6mogY0z8HOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:QLuJFQX92YUs6FCrqp2GFXZ8rpc=,iv:9Tm29zQePHyezdwmTEDht9+rKZANwBDHW1sgBGxkg2k=,tag:KbTtt7RHNUEuArvaCfGVdA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:yCiF4KLaZvYLeP9fXvD0OTr/CyUkrI/F6C7W19xg4uTt9tnphEUUDg==,iv:+/4/0kavBwE8uPPr3zQlCvJFYgDvjfzKHDv2OeVU7qc=,tag:bhi9ybc7j7xImYwaFo6r+A==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:Yr9Lkr7PPTHMRClWgXE=,iv:b21hHxSjdkGHrINRuDKilGol6Nh/S2+m2d7V35QOQfo=,tag:0ukXnVfcNeWcUgODnKWzVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWE1WS0NVekhybDhqbG1B
            YklKY1V5MWQwNXN3ZGYxY3Z2WFQrNzRQQ21ZCjhVUEZBMzM0c1hROWhzbC9pZmRY
            eVRYQWNrRW0rM1RJNExRUXlvdnpZSjgKLS0tIDNQQlN1TkNMTGVwc2hqaVhvdUdP
            TFlZMzRuTW5qakNaWWJvbmtCTXVreUkKVDTCdyT72+eEwgMPQaeYaChTso2Qchvn
            4gQby7fyI3GUfwBLc1vEeAhZqWi+0mputkvIeh01Rp2GS6Gou1bChg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-20T13:56:42Z"
    mac: ENC[AES256_GCM,data:1XDTg8MU8JJdwV4Jo+ZmdbLt0dwvcO2vubrMjZ2TDsUgjC2E4P5I0SFGvJQMUZHQoHGuyohCTtabBvjpAfTqAC8elFLta1zgeDvBASPkhxEP8mx4r2XZO+yZ4AuUKMgCNPW7Av6jD6S1RYCujftUw+INclHlwmsDHtjh4gQl82Q=,iv:EkPU0tQpCBiInzs2Yd1LvPImtvqy9RKkH3LDc9DbjxA=,tag:6Eex/8NG5sm6mogY0z8HOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
