apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname sonarr
  namespace: media
spec:
  releaseName: *appname
  chart:
    spec:
      chart: *appname
      version: "16.3.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 6m
  values:
    podLabels:
      app: *appname
    podSecurityContext:
      fsGroup: 568
      runAsUser: 0

    image:
      repository: ghcr.io/home-operations/sonarr
      tag: rolling@sha256:a986ef3682f1b94e2832a31ace57057279bd4ffdf49190a1b5f9f8d3cef875f5
      pullPolicy: Always
    
    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
    
    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8989
        type: ClusterIP
    
    persistence:
      config:
        enabled: true
        existingClaim: "sonarr-config-volume"
    
      downloads:
        enabled: true
        mountPropagation: HostToContainer
        existingClaim: downloads-mergerfs
        globalMounts:
          - path: /mnt/downloads
      media:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /mnt/media
      media-2:
        enabled: true
        mountPropagation: HostToContainer
        existingClaim: media-library-pvc
        globalMounts:
          - path: /mnt/media-smb


    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
          hajimari.io/group: "Media"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns.home.arpa/enabled: "true"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authentik@kubernetescrd
        hosts:
          - host: &uri "sonarr.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *uri
            secretName: *uri
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
---
