---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-smb
      version: v0.0.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb-charts
        namespace: flux-system
  values:
