id: whatsapp
url: "https://mautrix-whatsapp.${SECRET_DEV_DOMAIN}"
as_token: "${SECRET_MAUTRIX_WHATSAPP_AS_TOKEN}"
hs_token: "${SECRET_MAUTRIX_WHATSAPP_HS_TOKEN}"
sender_localpart: yqOEcpMsCMzYLD66kFUFZKi3cNEF1sSu
rate_limited: false
namespaces:
  users:
    - regex: ^@whatsappbot:dh274\.com$
      exclusive: true
    - regex: ^@whatsapp_.*:dh274\.com$
      exclusive: true
de.sorunome.msc2409.push_ephemeral: true
push_ephemeral: true
