apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games
commonLabels:
  app.kubernetes.io/name: &app games-on-whales
  app.kubernetes.io/instance: *app
resources:
  - helmrelease.yaml
