---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app grocy
  namespace: &ns utilities
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
          - "backend"

    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: docker.io/grocy/backend
              tag: v4.0.3-2
            envFrom:
              - configMapRef:
                  name: grocy-config
          frontend:
            image:
              repository: docker.io/grocy/frontend
              tag: v4.0.3-2
            envFrom:
              - configMapRef:
                  name: grocy-config

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        className: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &uri "grocy.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *uri
            secretName: *uri


    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: local-path
        size: 1Gi
        globalMounts:
          - path: /var/www/data
            subPath: *app
