apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
commonLabels:
  app.kubernetes.io/name: &app grocy
  app.kubernetes.io/instance: *app
resources:
  - helmrelease.yaml
  - configmap.yaml
