apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - ./system-upgrade/ks.yaml
  - ./utilities/reflector/ks.yaml
  # Databases
  - ./databases/redis/ks.yaml
    #  - ./databases/redis-operator/ks.yaml
  - ./databases/cloudnative-pg/ks.yaml
#  - ./databases/mariadb/ks.yaml
  #- ./databases/influxdb/ks.yaml
  #- ./databases/telegraf/ks.yaml

#  - ./kube-system/snapshot-controller/ks.yaml
  - ./kube-system/node-feature-discovery/ks.yaml
  - ./kube-system/intel-device-plugin/ks.yaml
#- ./kube-system/reloader
# - ./kube-system/descheduler

  # Storage
  - ./storage/nextcloud/ks.yaml
  - ./storage/gitea/ks.yaml
  #- ./storage/volsync/ks.yaml
  #- ./storage/kopia-web/ks.yaml
  #- ./storage/longhorn/ks.yaml
  - ./storage/minio/ks.yaml
    #- ./storage/nfs-provisioner
  - ./storage/csi-driver-smb/ks.yaml

  # Networking
  - ./networking/traefik/ks.yaml
  - ./networking/authentik/ks.yaml
    #- ./networking/authelia/ks.yaml
  - ./networking/cert-manager/ks.yaml
  - ./networking/metallb/ks.yaml
  - ./networking/external-dns/ks.yaml
    #- ./networking/multus/ks.yaml


  # Monitoring Namespace
  #- ./monitoring/flux
  - ./monitoring/prometheus-stack/ks.yaml
  - ./monitoring/weave-gitops/ks.yaml
  - ./monitoring/grafana/ks.yaml
    #- ./monitoring/loki/ks.yaml
      #   - ./monitoring/vector/ks.yaml

  # Default Namespace
 # - ./home/hajimari/ks.yaml

  # Media Namespace
  - ./media/jellyfin/ks.yaml
  #- ./media/ersatztv/ks.yaml
  #- ./media/tautulli/ks.yaml
  - ./media/sonarr/ks.yaml
  - ./media/radarr/ks.yaml
  - ./media/prowlarr/ks.yaml
  - ./media/flaresolverr/ks.yaml
  #- ./media/bazarr/ks.yaml
  #- ./media/readarr/ks.yaml
  #- ./media/nzbget/ks.yaml
  #- ./media/nzbhydra2/ks.yaml
  #- ./media/metube/ks.yaml
  #- ./media/mediarequests/ks.yaml
  #- ./media/calibre/ks.yaml
  #- ./media/outline/ks.yaml
  #- ./media/imaginary/ks.yaml

  # Utilities Namespace
 # - ./utilities/vaultwarden/ks.yaml
  #- ./utilities/vaultwarden-ldap/ks.yaml
  #- ./utilities/uptimekuma/ks.yaml
  #- ./utilities/smokeping/ks.yaml
  - ./utilities/changedetection/ks.yaml
  #- ./utilities/librespeed/ks.yaml
  #- ./utilities/guacamole/ks.yaml
  #- ./utilities/ltb-project/ks.yaml
  - ./utilities/pgadmin/ks.yaml
  - ./utilities/rumpreis/ks.yaml
  - ./utilities/httptoolkit/ks.yaml
  - ./utilities/rum_notifier/ks.yaml
  - ./utilities/grocy/ks.yaml
#  - ./utilities/podinfo/ks.yaml
#  - ./utilities/echo-server/ks.yaml
#
  - ./social/nginx-well-known/ks.yaml
  - ./social/nginx-test/ks.yaml
  - ./social/dendrite/ks.yaml
  - ./social/dendrite-shared/ks.yaml
  - ./social/signal-api/ks.yaml
  - ./games/satisfactory/ks.yaml
  - ./games/gravitas2/ks.yaml
  - ./utilities/zeropod/ks.yaml
  - ./games/gamesonwhales/ks.yaml
  - ./utilities/n8n/ks.yaml
