---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-volume
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 3Gi
---
