apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: redis-secret
    namespace: databases
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    host: ENC[AES256_GCM,data:9UogwhCeMGKIQ8fXTkJ7wkSD/orEt1mWdBN7GeUFNWjfchhN3jaKPbhTtW7thjjWkF5BCO4xoLBi7DMmK49nCSu8Bz3f0M1TI5kO7jksXaXOMb9cqRvYWLBdPoedUvLXOseh3n0JwAMt6oTQz29ysQ7QMhMvN7qSjvxVgiZb8u0ONdOFIqjRpIyR+ZU55MRIKg6L70h7oryS5Jo=,iv:u3l5WtiRf+FWIYkj1pEAQ48QAxHf2Su4SBLkh+H5LYI=,tag:rFcKyhW4+/SOh2w1eslr1A==,type:str]
    port: ENC[AES256_GCM,data:8awP88E/6mYsFQDiSWaByQ5mFA6zpRot0tmgYXowJ15mi3XrzyauPYfAYUTh3RGdw9t9ielYUnEPS+EJ7LGLXaG+4gjHVmmZ9qsjfNh2LiFurOnyTUP5Ps8MMgQ7hOfYZORlOu6Ge58PUB7bfLJQnbliwg==,iv:6iajU2m/Jx7/mcY658xtduFiNgFmrAdex6yGSRNMBNo=,tag:HToEo7Q6euq0QqrfGA7afg==,type:str]
    password: ENC[AES256_GCM,data:NYq14Z8ayfNpAA==,iv:Xy9vgMYbxnynIqdAJ8jES5mmoRvZ5qjPyUlyp3GhKro=,tag:5Vu7UpjusI6NL8QB0e8KfQ==,type:str]
    connstr: ENC[AES256_GCM,data:XwvSqVbcBY6UAKAPxxfiqOHyhOieTSFYuA+I3K9rlYFzrO/rj0M3WZYmaonI1SMyLzUsqX9Levstq31Wgjz79QGSao3KJSf0c0HTgPQGSIqXWN8B/1nUjkD567utAMNsLsdscG68/SMitMivUgl5xBD8GtGgHQNL7IytPsrk58RekJ6gNmOERr5jQzjho/eyylN/Ce7H7qOAUt4BJ9Noj8YoB+TizIFA/0NtM5WQ8/ryXIbVEaFjPjDyE+KhX1+LQG5+zKkMYQ==,iv:uK/bpp4D9wrSsU1UlrG8LWd3HX1RVtmtC9v2/xdDcfo=,tag:7ypvAGWyxpENL2YoGQcXOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRekJ2NFJoaStuYUEwOE9Z
            VFQwdlFQakVBQ0lDMmdVYmx4bHRGYmxycmpRCmplcktRYVdCWHgrcmpudzE0Nzdw
            Y3R1dzBiNm1ESHZBOEhkMEZ1bWZQWmMKLS0tIEk3ZjcwVmROclNOZ2NjaGVNK2FS
            dk00UFBYamtOTFpLVm83RVlKU0Y3V2cKUgX/kylt7oanNiYq/QP5TO4uelJqq1le
            9CD+15rSn538kNcqCEbZiS4SfU/NAA/r5CRjNTFfvwy/ss9Gqdhzhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-04T19:39:57Z"
    mac: ENC[AES256_GCM,data:EhnccTa56NG8AzCj36dXajrHBBc8BBKr24ln9Fc8wJuky7GscTklmvkm7ahXQHniemHrE31eTCHx4vgSBrtAGHdHyj7p9nFN6KhkEh61CcrJl7f9g/jiJvJrjNnHH707RtoQI3dU/1QwFbbeiHrpS28ZaZDuzFUc5nnuMboScBQ=,iv:NOSLW+pZzAFtPrQLcGuw2a2Bsu0J1r+4APSUVX3dctg=,tag:yTQBJdY64NGNUCGqTu39CQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
