apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
    namespace: storage
stringData:
    postgres_username: ENC[AES256_GCM,data:0Z0APEICkUWe,iv:VDJzcx07yu0IgraHn+t2aJQ+8agDzXFTIapolIwtbWs=,tag:hrG/UMmzW+WElmWgXzjDvA==,type:str]
    postgres_password: ENC[AES256_GCM,data:i6ULBKGAvEkhGhXJlw8=,iv:wg9XWwzcw2REFuW94jDKzlxn6TqvLJuekNJBHJ8bUXI=,tag:t+M+jftQvXXWI/gwUd0OpA==,type:str]
    gitea-username: ENC[AES256_GCM,data:d5IfqZHPpCjC,iv:c5DYItQzAmdDY4Kn4diX4qSbecAWAg01e85U1JC3pro=,tag:1EFnjv0M+zwmonjoL6Ea+A==,type:str]
    gitea-password: ENC[AES256_GCM,data:/1oFog/cT2BXzy47,iv:C2p96cFHLqxr2Ut843VvUAMWRWdjpHsVh/Ggd+gNJX0=,tag:exRRuP4r7oK2TySjf9BJ8g==,type:str]
    gitea-token: ENC[AES256_GCM,data:03ZtFULu2/brLBUKzQlK0CKH3LxlHONSG2n6WpcsbS4rpiN2xLRrIez1qoA=,iv:1OwCIGQ41Gd7sXXj0WiZJ62FOFbX921tzcRjOi3LYBw=,tag:J1px2ALbHDPSTZzofh0P9Q==,type:str]
    adminEmail: ENC[AES256_GCM,data:6FkgYxFMbM7kO0MpPX8E,iv:NP6qK30VwFreRI5MDfovZ8nIWto1Xb2nE6tPBaP0AUI=,tag:QJ9SNz6FWcTx9PVHwXjSsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRThIU0lFQVorZTV5SXp0
            dnVMNnJ6bGVsSmk3NFBnbkxUSkM0a3AxS2xRCkxKUWlvUTEwWjFSQTl6MGp0ZGZB
            eFNmTGEyS0ZHdVRPdWwxWVZwdm80SnMKLS0tIGo2a2k2OFZJODBock8yRUlPZXBo
            WGxyREdWNSsvWklrNFpaNVpwYTdTUXMKmbyv5ERzSdlGh49xaFFRv38VICdeJqN1
            USlgnCd2LcfJ5S/k6qdzighUBQkACVAD5jBimyL56/BalFJTkHTc/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-11T10:30:37Z"
    mac: ENC[AES256_GCM,data:1NJgcUhsksQBc7XEqVh3tGwRWJu4cH+0bjTMGR51VJ2415Uji3OBYxFpSX8cpwm2/U6rBlga87UPlNlzoykOR4eZ5fKXhk5E5tervCMkBGjrEERLlSj2V82les7vMk8+eRInqczctAaHZZQ8Th1UP2RTZIRHq5/Y/igbDFoXV5w=,iv:VEjq6li2KDiZjsykGcPOUQ/z4Fb3djGzVuQJMRr6Eeg=,tag:vwVa+rZ6vvMMTGtx0ngXGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
