apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: utilities
spec:
  releaseName: reflector
  chart:
    spec:
      chart: reflector
      version: 9.1.37
      sourceRef:
        kind: HelmRepository
        name: emberstack-charts
        namespace: flux-system
  interval: 6m
  install:
    remediation:
      retries: 7
  upgrade:
    remediation:
      retries: 7

