---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    adminUser:
      create: true
      createSecret: false
      username: admin
    ingress:
      enabled: true
      className: traefik
      annotations:
        external-dns.home.arpa/enabled: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        
      hosts:
        - host: "gitops.${SECRET_DEV_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix

      tls:
        - hosts:
          - &host "gitops.${SECRET_DEV_DOMAIN}"
          secretName: *host
    networkPolicy:
      create: false
    metrics:
      enabled: true
