apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:hSINC7fxAxZ+lC/0,iv:he7sO7dMDDo49MzYoOgfiTToIIzLHbYgl8KQFoNSHCs=,tag:smBaaNQRcdjKwe6X0iTvqw==,type:str]
    username: ENC[AES256_GCM,data:eEzVfoc=,iv:yHC+mV7883ANjLo8JVw5b1h9B4FbEoo9u5mNvncwTGo=,tag:h4TRMMg6mCqUbNe4I1jIkA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWkZZR0M3akZzVm1GNUVN
            d3hkQ1o5RWNTNkdudXZUM1lzdkdnRVU4M1NBCjhObmo5T0NyQ2Q5bGJScVlkclJG
            NUdFMkxBeWR5aFUvYmF5NWJIOEErMnMKLS0tIG5uRFhpQk1rRnpQcVZDcmZ3amt6
            RWRnZXUweVEyY0cvbFhEWmZ2UlRlb2cKbSg/xDadawrfcnONHyZaxg8rReqGARJ5
            mRZZHcK8WX1twjcASU0C5kycBDxeS3+/DofPX1j6dg8vISykxQQRCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T12:16:09Z"
    mac: ENC[AES256_GCM,data:HPckUJrrRsnMVJwUpMCbJsfjn92NbSPj9eGqYM5uwjzKYIDrIV6ptMb0WA42ajnURtUX2vEluuH9WE1D2dmXZgdfVVfLhHGG6Ri1VscpehhWjUAK3lpQRqlrYv9r0gozJhB8WIWn+/v/i8bM608m3J8ssHFEd7B3TR3qiDqRQq0=,iv:t8tCKItrhZQ6aP+Fa814QfH2ifv8b5UHeY51OXS3opM=,tag:9H13sU3sSdySydLfmu9rJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
