apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &appname mealie
  namespace: home
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/home-operations/postgres-init:rolling@sha256:a9f405688344a8a6f718e2c344438342ad21540986aeb5ab5fa781831eb2c597
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_SERVER
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_DB
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_USER
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_PASSWORD
