apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname mealie
  namespace: home
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/home-operations/postgres-init:rolling@sha256:894a38169bf4135fb1e85a1112c64fc24a267d1191887cbf6fb8c0a17893770d
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_SERVER
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_DB
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_USER
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_PASSWORD
