apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname mealie
  namespace: home
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/home-operations/postgres-init:rolling@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_SERVER
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_DB
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_USER
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_PASSWORD
