apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname mealie
  namespace: home
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/home-operations/postgres-init:rolling@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_SERVER
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_DB
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_USER
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: *appname
                key: POSTGRES_PASSWORD
