---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertiser
  namespace: networking
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: networking
spec:
  addresses:
  - 10.2.111.100-10.2.111.120
---
