apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mautrix-whatsapp
  namespace: social
spec:
  values:
    extraInitContainers:
      - name: init-db
        image: ghcr.io/home-operations/postgres-init:rolling@sha256:a9f405688344a8a6f718e2c344438342ad21540986aeb5ab5fa781831eb2c597
        env:
          #- name: POSTGRES_RESET # True - drops the table upon init if it exists
          #  value: "false"
          #- name: POSTGRES_RESET_CONFIRM # Are you sure you want to do this? 
          #  value: "NO"
          - name: POSTGRES_HOST
            value: defaultpg-rw.databases.svc.cluster.local
          - name: POSTGRES_DB
            value: *app
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: *app
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: *app
                key: POSTGRES_PASSWORD

