apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/instance: onlyoffice
  app.kubernetes.io/name: onlyoffice
kind: Kustomization
resources:
- helm-release.yaml
- middlewares.yaml
- secret.sops.yaml
