apiVersion: v1
kind: Secret
metadata:
    name: onlyoffice
    namespace: storage
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:H3mc3Egj09wQGF1qx4BP,iv:/jluaNdlX26WUH4cgZWt7pvTiQGctbPiUe0IwFzivzc=,tag:VZ3h+ePUqVFLE+yRM2lH/g==,type:str]
